# Generated by Django 4.1.5 on 2023-03-25 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_blogpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('assspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
