# Generated by Django 4.1.5 on 2023-03-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogviews_sno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogViews',
        ),
    ]
