# Generated by Django 4.1.5 on 2023-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogviews',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
